#!/bin/env bash
cp output.log tmp1.log
cat tmp1.log | python readlogs.py -w tmp1.json
echo 'Channel in logs'
cat tmp1.json | jq -r '.[].channel' | sort -u
python render_all_channels.py tmp1.json | less -R
